---
######################### Configure Host Repositories

  - name: Configure Host Repositories
    gather_facts: False
    include: ./config_repos.yml
    tags:
      - configure_repos | own_repos 
    when: use_opentlc_repos


  - name: Configure Host Repositories
    gather_facts: False
    include: ./subscription_manager_repos.yml
    tags:
      - configure_repos | subscription_manager_repos
    when: use_subscription_manager



######################### Install Basic Packages

  - name: Install Basic Packages
    gather_facts: False
    include: ./packages.yml
    tags:
      - install_basic_packages


######################### Run a complete yum update
  - name: Update all packages
    yum:
      name: '*'
      state: latest
