---
######################### Install Basic Packages
- name: install basic packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python
    - unzip
    - bash-completion
    - tmux
    - bind-utils
    - wget
    - ansible
    - git
    - vim-enhanced
  tags:
    - install_basic_packages
