---
## NFS specific


######################### Install OpenShift-Node Packages

  - name: Install openshift-node Packages
    gather_facts: False
    include: ./packages.yml
    tags:
      - install_openshift_node_packages


######################### Enable ntpd on openshift-node

  - name: Enable ntpd on openshift-node
    service:
      name: ntpd
      state: started
      enabled: yes
    tags:
      - enable_ntpd_on_host

######################### Install Docker (with storage) for OpenShift

  - name: Install docker with storage for OpenShift
    gather_facts: False
    include: ./install_docker_for_openshift.yml
    tags:
      - install_docker_for_openshift
