- name: install openshift_node packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
      - vim
      - tmux
      - ntp
      - wget
      - git
      - net-tools
      - bind-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - yum-versionlock
      - httpd-tools
  tags:
    - install_openshift_node_packages
