- name: install  packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
      - atomic-openshift-clients
      - atomic-openshift-utils
      - atomic-openshift
      - httpd-tools
  tags:
    - install_openshift_node_packages
